import Head from 'next/head'
import About from '../components/landing/about/about'
import Action from '../components/landing/action/action'
import Hero from '../components/landing/hero/hero'
import Work from '../components/landing/work/work'
import Footer from '../components/shared/footer/footer'
import Header from '../components/shared/header/header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Hero />
        <About />
        <Work />
        <Action />
      </main>

      <Footer />
    </div>
  )
}
